blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_published

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('list/<int:pk>/', BlogListView.as_view(), name='list'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('published/<int:pk>/', toggle_published, name='published'),
]

catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import contacts, ProductListView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('home', ProductListView.as_view(), name='home'),
    path('contacts/', contacts, name='contacts'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    body = models.CharField(max_length=150, verbose_name='Содержимое')
    slug = models.CharField(max_length=150, verbose_name='slug')
    preview = models.ImageField(upload_to='blog_media/', verbose_name='Превью блога', **NULLABLE)
    date_create = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        # Строковое отображение объекта
        return {self.title}

    class Meta:
        verbose_name = 'Блог'  # Настройка для наименования одного объекта
        verbose_name_plural = 'Блоги'  # Настройка для наименования набора объектов

catalog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Название категории')
    description = models.CharField(max_length=150, verbose_name='Описание категории')

    def __str__(self):
        # Строковое отображение объекта
        return f'{self.name} {self.description}'

    class Meta:
        verbose_name = 'Категория'  # Настройка для наименования одного объекта
        verbose_name_plural = 'Категории'  # Настройка для наименования набора объектов


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='Название продукта')
    description = models.CharField(max_length=150, verbose_name='Описание продукта')
    image = models.ImageField(upload_to='product_media/', verbose_name='Превью продукта', **NULLABLE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    price = models.IntegerField(default=0, verbose_name='Цена за покупку')
    date_create = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    date_modified = models.DateField(auto_now=True, verbose_name='Дата изменения')

    def __str__(self):
        # Строковое отображение объекта
        return f'{self.name} {self.description}'

    class Meta:
        verbose_name = 'Продукт'  # Настройка для наименования одного объекта
        verbose_name_plural = 'Продукты'  # Настройка для наименования набора объектов

blog/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from pytils.translit import slugify

from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'body', 'preview')
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'body',)

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


def toggle_published(request, pk):
    blog_item = get_object_or_404(Blog, pk=pk)
    if blog_item.is_published:
        blog_item.is_published = False
    else:
        blog_item.is_published = True

    blog_item.save()

    return redirect(reverse('blog:list'))

catalog/views.py
from django.shortcuts import render
from django.views.generic import ListView
from catalog.models import Product


class ProductListView(ListView):
    model = Product
    template_name = 'catalog/home.html'


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f"{name}  {phone}, {message}")
    return render(request, 'catalog/contacts.html')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load media_tags %}

{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                      <p>Хотите удалить блог "{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-primary">Подтвердить</button>
                      <a href="{% url 'blog:list' %}" class="btn btn-warning">Отмена</a>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load media_tags %}

{% block content %}

<div class="col-12">
    <div class="row">

        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        {{ object.title }} ({{ object.slug }})
                    </h3>
                </div>
                <div class="cord-body">
                    <p>
                        {{ object.body }}
                    </p>

                </div>
                <div class="card-footer">
                    Просмотры {{ object.views_count }}
                </div>
            </div>
        </div>
        <div class="col-6">
            <img src="{% mediapath object.preview %}" />
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load media_tags %}

{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                            Cохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load media_tags %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">YumYumStore</h1>
    <p class="lead">YumYumStore - лучший онлайн магазин продуктов</p>
    <a class="btn btn-primary" href="{% url 'blog:create' %}" role="button">Добавить новый блог</a>
</div>

<div class="container">

    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <img src="{% mediapath object.preview %}" class="card-img-top">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-5 mb-4 text-start m-3">
                        <li>- {{ object.body }}</li>
                    </ul>
                    <div class="btn=group">
                        <a class="btn btn-outline-primary" href="{% url 'blog:detail' object.pk %}" role="button">Посмотреть</a>
                        <a class="btn btn-outline-dark" href="{% url 'blog:update' object.pk %}"
                           role="button">Изменить</a>
                        <a class="btn btn-outline-danger" href="{% url 'blog:delete' object.pk %}" role="button">Удалить</a>
                    </div>
                    {% if object.is_published %}
                    <a  class="btn btn-warning" href="{% url 'blog:published' object.pk %}">Деактивировать</a>
                    {% else %}
                    <a class="btn btn-success" href="{% url 'blog:published' object.pk %}">Активировать</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>YumYumStore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">YumYumStore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:home' %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:list' %}">Статьи</a>
    </nav>
</div>

<div class="container">

    {% block content %}

    {% endblock %}

</div>

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            YumYumStore
            <small class="d-block mb-3 text-muted">&copy; 2023 - {% now 'Y' %}</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Фрукты</a></li>
                <li><a class="text-muted" href="#">Овощи</a></li>
                <li><a class="text-muted" href="#">Бобы</a></li>
                <li><a class="text-muted" href="#">Рассада</a></li>
                <li><a class="text-muted" href="#">Всё, что захотите</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% load static %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Контактный телефон" required></textarea>
                        </div>
                        <input type="submit" value="Отправить">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load media_tags %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">YumYumStore</h1>
    <p class="lead">YumYumStore - лучший онлайн магазин продуктов</p>
</div>

<div class="container">

    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow" >
                <img src="{% mediapath object.image %}" class="card-img-top">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ object.price }} ₽</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ object.description }}</li>

                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}